questions =  [
    {"id": 0, "question": "A strong military is necessary for a state to succeed.", "effects": {"right": 1}},
    {"id": 1, "question": "I believe in mandatory conscription.", "effects": {"right": 1}},
    {"id": 2, "question": "Too many people are skipping their military service nowadays.", "effects": {"right": 1}},
    {"id": 3, "question": "Conscientious objectors and Ultra-Orthodox Jews should be jailed for refusing to serve.", "effects": {"right": 1}},
    {"id": 4, "question": "Military service is an important part of becoming an adult.", "effects": {"right": 1}},
    {"id": 5, "question": "I believe in harsher punishments for terrorists, such as house-demolition and the death penalty.", "effects": {"right": 1}},
    {"id": 6, "question": "The military rule over the Palestinians is necessary, even if it limits their civil liberties.", "effects": {"right": 1}},
    {"id": 7, "question": "In case of an emergency, the IDF should carry out policing.", "effects": {"right": 1}},
    {"id": 8, "question": "Retired generals should not go into politics.", "effects": {"right": -1}},
    {"id": 9, "question": "Mandatory conscription is harmful and should be abolished.", "effects": {"right": -1}},
    {"id": 10, "question": "Administrative detention should be outlawed.", "effects": {"right": -1}},
    {"id": 11, "question": "Any person should have the right not to serve in the IDF.", "effects": {"right": -1}},
    {"id": 12, "question": "Our society is overly militarized.", "effects": {"right": -1}},
    {"id": 13, "question": "Insurgents who only target soldiers should not be considered terrorists.", "effects": {"right": -1}},
    {"id": 14, "question": "Some Israeli officials should face prosecution for war crimes.", "effects": {"right": -1}},
    {"id": 15, "question": "Jews are a people, not just a religion.", "effects": {"auth": 1}},
    {"id": 16, "question": "All Israelis should use Hebrew in day to day life.", "effects": {"auth": 1}},
    {"id": 17, "question": "Jews are indigenous to this land.", "effects": {"auth": 1}},
    {"id": 18, "question": "It is important to protect the Jewish nature of the State of Israel.", "effects": {"auth": 1}},
    {"id": 19, "question": "The Land of Israel belongs exclusively to the Jewish people.", "effects": {"auth": 1}},
    {"id": 20, "question": "Jews should not marry Arabs and non-Jews in general.", "effects": {"auth": 1}},
    {"id": 21, "question": "Jewish kids should to study Arabic in school.", "effects": {"auth": 1}},
    {"id": 22, "question": "Arab and Jewish children should study separately.", "effects": {"auth": 1}},
    {"id": 23, "question": "The Israeli government committed a \"cultural genocide\" of Arab Jews.", "effects": {"auth": -1}},
    {"id": 24, "question": "Israel should be a state of all its citizens.", "effects": {"auth": -1}},
    {"id": 25, "question": "The Law of Return is unnecessary and should be abolished.", "effects": {"auth": -1}},
    {"id": 26, "question": "Jews should not be referred to as one ethnic group.", "effects": {"auth": -1}},
    {"id": 27, "question": "The Nation-State Law should be abolished.", "effects": {"auth": -1}},
    {"id": 28, "question": "Israel cannot be democratic as long as the Palestinians cannot vote.", "effects": {"auth": -1}},
    {"id": 29, "question": "Non-Jewish immigrant children should be considered Israeli and have equal rights to Jewish Israelis.", "effects": {"auth": -1}},
    {"id": 30, "question": "Respecting a person means respecting their pronouns, too.", "effects": {"prog": 1}},
    {"id": 31, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}},
    {"id": 32, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
    {"id": 33, "question": "The Rabbinate should be abolished.", "effects": {"prog": 1}},
    {"id": 34, "question": "Animals deserve certain universal rights.", "effects": {"prog": 1}},
    {"id": 35, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 36, "question": "Civil and mixed marriage should be legalized.", "effects": {"prog": 1}},
    {"id": 37, "question": "Our justice system should focus on reforming criminals more than punishing them.", "effects": {"prog": 1}},
    {"id": 38, "question": "Homosexuality is against my values.", "effects": {"prog": -1}},
    {"id": 39, "question": "Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}},
    {"id": 40, "question": "Non-medical use of certain drugs should be legalized.", "effects": {"prog": -1}},
    {"id": 41, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 42, "question": "Changing the Hebrew language in the name of inclusivity only butchers the language.", "effects": {"prog": -1}},
    {"id": 43, "question": "Studying religion and tradition should be mandatory in Israeli schools.", "effects": {"prog": -1}},
    {"id": 44, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
    {"id": 45, "question": "Abortion is immoral.", "effects": {"prog": -1}}
];
